services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    volumes:
      - .:/project
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - MYSQL_HOST=db
      - MYSQL_DATABASE=main
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0605
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 20050605
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: 0605
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  mysql_data:
