services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    env_file:
      - .env  # ここで .env ファイルを指定します
    command: gunicorn  project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./project:/project
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - MYSQL_HOST=db
      - MYSQL_DATABASE=main
      - MYSQL_USER=takato
      - MYSQL_PASSWORD=0605
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 20050605
      MYSQL_DATABASE: main
      MYSQL_USER: takato
      MYSQL_PASSWORD: 0605
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - db

volumes:
  mysql_data:
