services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # entrypoint: /bin/sh
    container_name: web
    env_file:
      - .env  # ここで .env ファイルを指定します
    command: gunicorn  project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./project:/project
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=project.settings
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=mysql://takato:0605@db:3306/main
      - DATABASE_HOST=db
      - DATABASE_NAME=main
      - DATABASE_USER=takato
      - DATABASE_PASSWORD=0605
    depends_on:
      db:
        condition: service_healthy
    networks:
    - webnet

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=20050605
      - MYSQL_DATABASE=main
      - MYSQL_USER=takato
      - MYSQL_PASSWORD=0605
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./project/static:/project/static
    depends_on:
      - web
    networks:
    - webnet

volumes:
  mysql_data:
networks:
  webnet:
    driver: bridge