# Generated by Django 5.1 on 2024-08-30 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Class名')),
                ('category', models.CharField(max_length=15, null=True, verbose_name='カテゴリ')),
                ('web_site', models.URLField(blank=True)),
                ('backimage', models.ImageField(upload_to='backimage/', verbose_name='BackImage')),
                ('icon', models.ImageField(null=True, upload_to='classicon/', verbose_name='クラスアイコン')),
                ('index', models.CharField(max_length=50, null=True, verbose_name='見出し')),
                ('explain', models.TextField(blank=True, max_length=180, verbose_name='explain')),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('mainuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='メインユーザー')),
                ('managername', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='管理者')),
            ],
            options={
                'verbose_name_plural': 'ClassName',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='post/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='投稿先')),
                ('mainuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='メインユーザー')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='投稿主')),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
