# Generated by Django 5.1 on 2024-09-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0002_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='mainteam',
        ),
        migrations.RemoveField(
            model_name='network',
            name='subteam',
        ),
    ]
