# Generated by Django 5.1 on 2024-09-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0003_remove_network_mainteam_remove_network_subteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('local', 'Local')], default='public', max_length=10, verbose_name='可視性'),
        ),
    ]
