# Generated by Django 5.1 on 2024-09-03 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0004_network_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='mygroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='ハブ'),
        ),
        migrations.AlterField(
            model_name='network',
            name='index',
            field=models.CharField(max_length=80, null=True, verbose_name='見出し'),
        ),
        migrations.CreateModel(
            name='AddNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flexblock.network', verbose_name='ネットワーク名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='')),
            ],
        ),
    ]
