# Generated by Django 5.1 on 2024-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0005_network_mygroup_alter_network_index_addnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addnetwork',
            options={'verbose_name_plural': 'add-network'},
        ),
        migrations.AddField(
            model_name='addnetwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
    ]
