# Generated by Django 5.1 on 2024-09-05 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0007_rootauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootauth',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests_received', to='accounts.account'),
        ),
    ]
