# Generated by Django 5.1 on 2024-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0009_alter_rootauth_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('local', 'Local')], default='public', max_length=10, verbose_name='可視性'),
        ),
    ]
