# Generated by Django 5.1 on 2024-09-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0010_group_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
