# Generated by Django 5.1 on 2024-09-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0011_alter_group_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'ClassName'},
        ),
    ]
