# Generated by Django 5.1 on 2024-09-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0014_alter_groupmembership_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='ユーザー名'),
        ),
    ]
