# Generated by Django 5.1 on 2024-09-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0015_alter_groupmembership_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnetwork',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='ターゲットグループ'),
        ),
    ]
