# Generated by Django 5.1 on 2024-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0016_alter_addnetwork_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='target_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='ターゲット', to='flexblock.group'),
        ),
    ]
