# Generated by Django 5.1 on 2024-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0017_network_target_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='target_group',
            field=models.ManyToManyField(blank=True, related_name='ターゲット', to='flexblock.group'),
        ),
    ]
