# Generated by Django 5.1 on 2024-09-07 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0018_alter_network_target_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': 'ClassName'},
        ),
        migrations.RemoveField(
            model_name='network',
            name='mygroup',
        ),
        migrations.RemoveField(
            model_name='network',
            name='target_group',
        ),
        migrations.AddField(
            model_name='network',
            name='explain',
            field=models.TextField(blank=True, max_length=180, verbose_name='explain'),
        ),
        migrations.AddField(
            model_name='network',
            name='managername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='network',
            name='index',
            field=models.CharField(max_length=50, null=True, verbose_name='見出し'),
        ),
        migrations.AlterField(
            model_name='network',
            name='mainuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='メインユーザー'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Network名'),
        ),
        migrations.DeleteModel(
            name='AddNetwork',
        ),
    ]
