# Generated by Django 5.1 on 2024-09-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0019_alter_network_options_remove_network_mygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='mygroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='ハブ'),
        ),
        migrations.AddField(
            model_name='network',
            name='target_group',
            field=models.ManyToManyField(blank=True, related_name='ターゲット', to='flexblock.group'),
        ),
    ]
