# Generated by Django 5.1 on 2024-09-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0020_network_mygroup_network_target_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name_plural': 'Network'},
        ),
        migrations.RemoveField(
            model_name='network',
            name='explain',
        ),
    ]
