# Generated by Django 5.1 on 2024-09-07 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0022_remove_network_managername_remove_network_mygroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ハブグループ名', to='flexblock.group'),
        ),
    ]
