# Generated by Django 5.1 on 2024-09-15 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0024_alter_post_destination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexblock.group', verbose_name='投稿先'),
        ),
        migrations.CreateModel(
            name='NetworkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='post/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexblock.network', verbose_name='投稿先')),
                ('mainuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='メインユーザー')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='投稿主')),
            ],
            options={
                'verbose_name_plural': 'NetworkPost',
            },
        ),
    ]
