# Generated by Django 5.1 on 2024-09-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0025_alter_post_destination_networkpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Making',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日')),
                ('hub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ハブグループ', to='flexblock.group')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ネットワーク名', to='flexblock.network')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='サブグループ', to='flexblock.group')),
            ],
            options={
                'verbose_name_plural': 'Making',
            },
        ),
    ]
