# Generated by Django 5.1 on 2024-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0032_alter_making_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnetwork',
            name='created_at',
        ),
        migrations.AddField(
            model_name='addnetwork',
            name='is_approved_by_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addnetwork',
            name='is_approved_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
