# Generated by Django 5.1 on 2024-09-23 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0033_remove_addnetwork_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='making',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ハブグループ', to='flexblock.group'),
        ),
        migrations.AlterField(
            model_name='making',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ネットワーク名', to='flexblock.network'),
        ),
        migrations.AlterField(
            model_name='making',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='サブグループ', to='flexblock.group'),
        ),
    ]
