# Generated by Django 5.1 on 2024-09-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0034_alter_making_hub_alter_making_name_alter_making_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='group',
            name='comanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flexblock.rootauth', verbose_name='共同管理'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('single', 'シングル'), ('multiple', 'マルチ')], default='single', max_length=10, verbose_name='タイプ'),
        ),
    ]
