# Generated by Django 5.1 on 2024-09-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0035_remove_group_transaction_hash_group_comanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='comanager',
        ),
        migrations.AddField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, null=True, to='flexblock.rootauth', verbose_name='共同管理'),
        ),
    ]
