# Generated by Django 5.1 on 2024-09-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0037_remove_group_comanager_remove_group_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='group',
            name='icon',
        ),
        migrations.AlterField(
            model_name='group',
            name='index',
            field=models.CharField(max_length=100, null=True, verbose_name='見出し'),
        ),
    ]
