# Generated by Django 5.1 on 2024-09-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0038_remove_group_explain_remove_group_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('single', 'シングル'), ('multiple', 'マルチ')], default='single', max_length=10, verbose_name='タイプ'),
        ),
    ]
