# Generated by Django 5.1 on 2024-09-23 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0039_group_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='共同管理', to='accounts.account'),
        ),
    ]
