# Generated by Django 5.1 on 2024-09-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0041_alter_group_comanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='comanager',
        ),
        migrations.AddField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, null=True, related_name='共同管理', to='flexblock.rootauth'),
        ),
    ]
