# Generated by Django 5.1 on 2024-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('flexblock', '0042_remove_group_comanager_group_comanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, null=True, related_name='共同管理', to='accounts.account'),
        ),
    ]
