# Generated by Django 5.1 on 2024-09-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0044_alter_group_comanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootauth',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
