# Generated by Django 5.1 on 2024-09-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0045_rootauth_is_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnetwork',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
