# Generated by Django 5.1 on 2024-09-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0048_remove_group_comanager_remove_group_group_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cogroup',
            name='mainuser',
        ),
    ]
