# Generated by Django 5.1 on 2024-09-29 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0049_remove_cogroup_mainuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoGroup',
        ),
    ]
