# Generated by Django 5.1 on 2024-09-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0051_group_comanager_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('single', 'シングル'), ('multiple', 'マルチ')], default='single', max_length=10, verbose_name='タイプ'),
        ),
    ]
