# Generated by Django 5.1 on 2024-09-30 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0053_group_mainusers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mainusers',
            field=models.ManyToManyField(blank=True, related_name='共同管理者', to=settings.AUTH_USER_MODEL),
        ),
    ]
