# Generated by Django 5.1 on 2024-09-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0054_alter_group_mainusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='mainusers',
        ),
    ]
