# Generated by Django 5.1 on 2024-09-30 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0055_remove_group_mainusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
