# Generated by Django 5.1 on 2024-10-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_admin_alter_customuser_email_and_more'),
        ('flexblock', '0061_alter_group_comanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='managername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='管理者'),
        ),
    ]
