# Generated by Django 5.1 on 2024-10-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_first_name_and_more'),
        ('flexblock', '0065_alter_group_comanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='comanager',
        ),
        migrations.AddField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, null=True, related_name='rootauths', to='accounts.account'),
        ),
    ]
