# Generated by Django 5.1 on 2024-10-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexblock', '0066_remove_group_comanager_group_comanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Class名'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Network名'),
        ),
    ]
