# Generated by Django 5.1 on 2024-10-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_first_name_and_more'),
        ('flexblock', '0067_alter_group_name_alter_network_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, related_name='rootauths', to='accounts.account'),
        ),
    ]
