# Generated by Django 5.1 on 2024-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_first_name_and_more'),
        ('flexblock', '0069_alter_group_comanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='comanager',
            field=models.ManyToManyField(blank=True, related_name='rootauths', to='accounts.account'),
        ),
    ]
