# Generated by Django 5.1 on 2024-10-14 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_first_name_and_more'),
        ('flexblock', '0070_alter_group_comanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootauth',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests_received', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='rootauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests_sent', to='accounts.account'),
        ),
    ]
